#baseurl:        http://www.edrooth.com/jekyll-bootstrap
plugins:        _plugins
markdown:       rdiscount
pygments:       true
permalink:      /blog/:year/:month/:day/:title
title:          Your Awesome Blog
description:    This site is so rad becuase it uses Jekyll-Bootstrap!
author:         Your Name
#analyticsid:    UA-GGGGG-G
#disqusname:
#twittername:
